services: 
  maptiler:
    image: maptiler
    container_name: maptiler
    ports:
      - 3650:3650
    mem_limit: 500m
  position-provider:
    image: position-provider
    container_name: position-provider
    ports:
        - '5000:5000'
        - '5001:5001'
    environment:
        - 'ASPNETCORE_HTTP_PORT=http://+:5001'
        - 'ASPNETCORE_URLS=http://+:5000'
    mem_limit: 300m
  mock-position-provider:
    image: mock-position-provider
    container_name: mock-position-provider
    ports:
        - '9000:9000'
        - '9001:9001'
        - '7000:7000'
    environment:
        - 'ASPNETCORE_HTTP_PORT=http://+:9001'
        - 'ASPNETCORE_URLS=http://+:9000'
    mem_limit: 300m
    depends_on:
      - mapbox
  mapbox:
    container_name: frontend
    ports:
        - '3000:3000'
    image: mapbox:latest
    mem_limit: 900m
    depends_on:
      - maptiler
  watchdog:
    container_name: watchdog
    image: watchdog
    mem_limit: 500m
    depends_on:
      - mock-position-provider
  selfdata:
    container_name: selfdata
    ports:
        - '4000:4000'
    image: selfdata
    mem_limit: 100m
