services: 
  maptiler:
    image: maptiler
    container_name: maptiler
    ports:
      - 3650:3650
    mem_limit: 500m
  position-provider:
    image: position-provider
    container_name: position-provider
    ports:
        - '5000:5000'
        - '5001:5001'
    environment:
        - 'ASPNETCORE_HTTP_PORT=http://+:5001'
        - 'ASPNETCORE_URLS=http://+:5000'
    mem_limit: 300m
  mock-self-data:
    image: mock-self-data
    container_name: mock-self-data
    ports:
        - '9000:9000'
        - '9001:9001'
        - '7000:7000'
        - '7001:7001'
    environment:
        - 'ASPNETCORE_HTTP_PORT=http://+:9001'
        - 'ASPNETCORE_URLS=http://+:9000'
    mem_limit: 300m
    depends_on:
      - mapbox
  mapbox:
    container_name: frontend
    ports:
        - '3000:3000'
    image: frontend:latest
    mem_limit: 900m
    depends_on:
      - maptiler
